spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: psb011031!
    url: jdbc:mysql://localhost:3306/login-project?serverTimezone=Asia/Seoul
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true
