spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: psb011031!
    url: jdbc:mysql://database-ex.cxua8wo0mbwg.ap-northeast-2.rds.amazonaws.com/mydatabase?serverTimezone=Asia/Seoul
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true
